from crewai import Task

def create_tasks(researcher, copywriter, fact_checker, editor):
    research_task = Task(
        description=(
            "Research the topic: {topic}. "
            "Identify 3 key insights and 1 unique angle that would make for viral content."
        ),
        expected_output="A detailed research report with key insights and a unique angle.",
        agent=researcher
    )

    copywriting_task = Task(
        description=(
            "Using the research provided, create a content plan that includes: "
            "1. An X thread (5-7 tweets) "
            "2. A LinkedIn post "
            "3. A Newsletter summary "
            "The content must be engaging and tailored to each platform's audience."
        ),
        expected_output="A multi-platform content plan including an X thread, LinkedIn post, and Newsletter summary.",
        agent=copywriter
    )

    fact_checking_task = Task(
        description=(
            "Review the content plan generated by the copywriter. "
            "Cross-reference every claim with the researcher's report. "
            "If any claim is not supported by the research, rewrite it to be accurate. "
            "Focus on maintaining high groundedness."
        ),
        expected_output="An audited content plan where all claims are verified against the research.",
        agent=fact_checker
    )

    editing_task = Task(
        description=(
            "Review the audited content plan for SEO optimization, clarity, and brand consistency. "
            "Ensure the tone is professional yet engaging."
        ),
        expected_output="The final, polished content plan ready for publication.",
        agent=editor
    )

    return [research_task, copywriting_task, fact_checking_task, editing_task]
